In [3]:
import numpy as np
import pandas as pd

In [4]:
ratings = pd.read_table('data/ml-1m/ratings.dat', header=None, names=['UserID', 'MovieID', 'Rating', 'Timestamp'], sep='::')
users = pd.read_table('data/ml-1m/users.dat', header=None, names=['UserID','Gender','Age','Occupation','Zip-code'], sep='::')
movies = pd.read_table('data/ml-1m/movies.dat', header=None, names=['MovieID', 'Title', 'Genres'], sep='::')

C:\Users\regdz\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.
C:\Users\regdz\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

C:\Users\regdz\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  This is separate from the ipykernel package so we can avoid doing imports until

In [5]:
ratings.head()

   UserID  MovieID  Rating  Timestamp
0       1     1193       5  978300760
1       1      661       3  978302109
2       1      914       3  978301968
3       1     3408       4  978300275
4       1     2355       5  978824291

In [6]:
users.head()

   UserID Gender  Age  Occupation Zip-code
0       1      F    1          10    48067
1       2      M   56          16    70072
2       3      M   25          15    55117
3       4      M   45           7    02460
4       5      M   25          20    55455

In [7]:
movies.head()

   MovieID                               Title                        Genres
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy

In [8]:
data = pd.merge(pd.merge(users, ratings), movies)
data.head()

,UserID,Gender,Age,Occupation,Zip-code,MovieID,Rating,Timestamp,Title,Genres
0,1,F,1,10,48067,1193,5,978300760,One Flew Over the Cuckoo's Nest (1975),Drama
1,2,M,56,16,70072,1193,5,978298413,One Flew Over the Cuckoo's Nest (1975),Drama
2,12,M,25,12,32793,1193,4,978220179,One Flew Over the Cuckoo's Nest (1975),Drama
3,15,M,25,7,22903,1193,4,978199279,One Flew Over the Cuckoo's Nest (1975),Drama
4,17,M,50,1,95350,1193,5,978158471,One Flew Over the Cuckoo's Nest (1975),Drama

In [9]:
print(data[data.UserID == 1].head())

      UserID Gender  Age  Occupation Zip-code  MovieID  Rating  Timestamp  \
0          1      F    1          10    48067     1193       5  978300760
1725       1      F    1          10    48067      661       3  978302109
2250       1      F    1          10    48067      914       3  978301968
2886       1      F    1          10    48067     3408       4  978300275
4201       1      F    1          10    48067     2355       5  978824291

                                       Title                        Genres
0     One Flew Over the Cuckoo's Nest (1975)                         Drama
1725        James and the Giant Peach (1996)  Animation|Children's|Musical
2250                     My Fair Lady (1964)               Musical|Romance
2886                  Erin Brockovich (2000)                         Drama
4201                    Bug's Life, A (1998)   Animation|Children's|Comedy

In [10]:
# 生成透视表
data_gender = data.pivot_table(values='Rating', index='Title', columns='Gender', aggfunc='mean')
data_gender.head()

Gender                                F         M
Title
$1,000,000 Duck (1971)         3.375000  2.761905
'Night Mother (1986)           3.388889  3.352941
'Til There Was You (1997)      2.675676  2.733333
'burbs, The (1989)             2.793478  2.962085
...And Justice for All (1979)  3.828571  3.689024

In [39]:
data_gender['difference'] = data_gender.F - data_gender.M
data_gender_sorted = data_gender.sort_values(by='difference', ascending=False)
data_gender_sorted

Gender,F,M,difference
Title,,,
"James Dean Story, The (1957)",4.000000,1.000000,3.000000
"Spiders, The (Die Spinnen, 1. Teil: Der Goldene See) (1919)",4.000000,1.000000,3.000000
Country Life (1994),5.000000,2.000000,3.000000
Babyfever (1994),3.666667,1.000000,2.666667
"Woman of Paris, A (1923)",5.000000,2.428571,2.571429
Cobra (1925),4.000000,1.500000,2.500000
"Other Side of Sunday, The (S鴑dagsengler) (1996)",5.000000,2.928571,2.071429
Theodore Rex (1995),3.000000,1.000000,2.000000
For the Moment (1994),5.000000,3.000000,2.000000
"Separation, The (La S閜aration) (1994)",4.000000,2.000000,2.000000
"To Have, or Not (1995)",4.000000,2.000000,2.000000
Mad Dog Time (1996),4.000000,2.000000,2.000000
"Crude Oasis, The (1995)",3.000000,1.000000,2.000000
Coming Apart (1969),4.000000,2.000000,2.000000
Belly (1998),5.000000,3.000000,2.000000
Phat Beach (1996),3.000000,1.000000,2.000000
"Reluctant Debutante, The (1958)",3.857143,2.000000,1.857143
"Gambler, The (A J醫閗os) (1997)",5.000000,3.166667,1.833333
"Thin Line Between Love and Hate, A (1996)",4.000000,2.166667,1.833333
"Acid House, The (1998)",4.000000,2.200000,1.800000
Twice Upon a Yesterday (1998),5.000000,3.222222,1.777778
Battling Butler (1926),5.000000,3.222222,1.777778
Dancemaker (1998),5.000000,3.250000,1.750000
Panther (1995),4.666667,2.920000,1.746667
"Savage Nights (Nuits fauves, Les) (1992)",4.000000,2.285714,1.714286
Raw Deal (1948),5.000000,3.307692,1.692308
"Marcello Mastroianni: I Remember Yes, I Remember (1997)",4.666667,3.000000,1.666667
Horror Hotel (a.k.a. The City of the Dead) (1960),3.000000,1.333333,1.666667
Trippin' (1999),4.000000,2.333333,1.666667
Kissed (1996),4.333333,2.700000,1.633333
...,...,...,...
Tokyo Fist (1995),NaN,2.500000,NaN
Tough and Deadly (1995),NaN,2.000000,NaN
Trans (1998),NaN,3.000000,NaN
Trois (2000),NaN,2.000000,NaN
Two Thousand Maniacs! (1964),NaN,3.266667,NaN
"Ugly, The (1997)",NaN,1.888889,NaN
Ulysses (Ulisse) (1954),NaN,5.000000,NaN
Underworld (1997),NaN,1.000000,NaN
"Uninvited Guest, An (2000)",NaN,1.000000,NaN
Vampyros Lesbos (Las Vampiras) (1970),NaN,3.333333,NaN
Venice/Venice (1992),NaN,1.000000,NaN
"Very Natural Thing, A (1974)",NaN,3.333333,NaN
Voyage to the Beginning of the World (1997),NaN,4.000000,NaN
"Waiting Game, The (2000)",NaN,2.000000,NaN
"Walking Dead, The (1995)",NaN,2.684211,NaN
Waltzes from Vienna (1933),NaN,1.000000,NaN
"War at Home, The (1996)",NaN,2.500000,NaN
Wedding Bell Blues (1996),3.250000,NaN,NaN
Wend Kuuni (God's Gift) (1982),NaN,4.000000,NaN
Where's Marlowe? (1999),NaN,4.000000,NaN
White Boys (1999),NaN,1.000000,NaN
Wild Bill (1995),NaN,3.146341,NaN
Windows (1980),NaN,1.000000,NaN
Wings of Courage (1995),NaN,3.000000,NaN
With Byrd at the South Pole (1930),NaN,2.000000,NaN
With Friends Like These... (1998),NaN,4.000000,NaN
"Wooden Man's Bride, The (Wu Kui) (1994)",NaN,3.000000,NaN
Year of the Horse (1997),NaN,3.250000,NaN
Zachariah (1971),NaN,3.500000,NaN
Zero Kelvin (Kj鎟lighetens kj鴗ere) (1995),NaN,3.500000,NaN

In [40]:
# 平均分
data_mean_rating = data.pivot_table(values='Rating', index='Title', aggfunc='mean')
data_mean_rating_sorted = data_mean_rating.sort_values(by='Rating', ascending=False)
data_mean_rating_sorted

                                                      Rating
Title
Ulysses (Ulisse) (1954)                             5.000000
Lured (1947)                                        5.000000
Follow the Bitch (1998)                             5.000000
Bittersweet Motel (2000)                            5.000000
Song of Freedom (1936)                              5.000000
One Little Indian (1973)                            5.000000
Smashing Time (1967)                                5.000000
Schlafes Bruder (Brother of Sleep) (1995)           5.000000
Gate of Heavenly Peace, The (1995)                  5.000000
Baby, The (1973)                                    5.000000
I Am Cuba (Soy Cuba/Ya Kuba) (1964)                 4.800000
Lamerica (1994)                                     4.750000
Apple, The (Sib) (1998)                             4.666667
Sanjuro (1962)                                      4.608696
Seven Samurai (The Magnificent Seven) (Shichini...  4.560510
Shawshank Redemption, The (1994)                    4.554558
Godfather, The (1972)                               4.524966
Close Shave, A (1995)                               4.520548
Usual Suspects, The (1995)                          4.517106
Schindler's List (1993)                             4.510417
Wrong Trousers, The (1993)                          4.507937
Dry Cleaning (Nettoyage � sec) (1997)               4.500000
Inheritors, The (Die Siebtelbauern) (1998)          4.500000
Mamma Roma (1962)                                   4.500000
Bells, The (1926)                                   4.500000
Dangerous Game (1993)                               4.500000
Hour of the Pig, The (1993)                         4.500000
Callej髇 de los milagros, El (1995)                  4.500000
Skipped Parts (2000)                                4.500000
Sunset Blvd. (a.k.a. Sunset Boulevard) (1950)       4.491489
...                                                      ...
Diebinnen (1995)                                    1.000000
Blood Spattered Bride, The (La Novia Ensangrent...  1.000000
Bloody Child, The (1996)                            1.000000
Uninvited Guest, An (2000)                          1.000000
Little Indian, Big City (Un indien dans la vill...  1.000000
Shadows (Cienie) (1988)                             1.000000
McCullochs, The (1975)                              1.000000
Hillbillys in a Haunted House (1967)                1.000000
Terror in a Texas Town (1958)                       1.000000
White Boys (1999)                                   1.000000
Lotto Land (1995)                                   1.000000
Nueba Yol (1995)                                    1.000000
Even Dwarfs Started Small (Auch Zwerge haben kl...  1.000000
Get Over It (1996)                                  1.000000
Venice/Venice (1992)                                1.000000
Sleepover (1995)                                    1.000000
Silence of the Palace, The (Saimt el Qusur) (1994)  1.000000
Waltzes from Vienna (1933)                          1.000000
Wirey Spindell (1999)                               1.000000
Kestrel's Eye (Falkens 鰃a) (1998)                   1.000000
Spring Fever USA (a.k.a. Lauderdale) (1989)         1.000000
Loves of Carmen, The (1948)                         1.000000
Underworld (1997)                                   1.000000
Low Life, The (1994)                                1.000000
Santa with Muscles (1996)                           1.000000
Fantastic Night, The (La Nuit Fantastique) (1949)   1.000000
Cheetah (1989)                                      1.000000
Torso (Corpi Presentano Tracce di Violenza Carn...  1.000000
Mutters Courage (1995)                              1.000000
Windows (1980)                                      1.000000

[3706 rows x 1 columns]

In [41]:
# 评论最热门
data_rating_num = data.groupby('Title').size()
data_rating_num_sorted = data_rating_num.sort_values(ascending=False)
data_rating_num_sorted

Title
American Beauty (1999)                                                   3428
Star Wars: Episode IV - A New Hope (1977)                                2991
Star Wars: Episode V - The Empire Strikes Back (1980)                    2990
Star Wars: Episode VI - Return of the Jedi (1983)                        2883
Jurassic Park (1993)                                                     2672
Saving Private Ryan (1998)                                               2653
Terminator 2: Judgment Day (1991)                                        2649
Matrix, The (1999)                                                       2590
Back to the Future (1985)                                                2583
Silence of the Lambs, The (1991)                                         2578
Men in Black (1997)                                                      2538
Raiders of the Lost Ark (1981)                                           2514
Fargo (1996)                                                             2513
Sixth Sense, The (1999)                                                  2459
Braveheart (1995)                                                        2443
Shakespeare in Love (1998)                                               2369
Princess Bride, The (1987)                                               2318
Schindler's List (1993)                                                  2304
L.A. Confidential (1997)                                                 2288
Groundhog Day (1993)                                                     2278
E.T. the Extra-Terrestrial (1982)                                        2269
Star Wars: Episode I - The Phantom Menace (1999)                         2250
Being John Malkovich (1999)                                              2241
Shawshank Redemption, The (1994)                                         2227
Godfather, The (1972)                                                    2223
Forrest Gump (1994)                                                      2194
Ghostbusters (1984)                                                      2181
Pulp Fiction (1994)                                                      2171
Terminator, The (1984)                                                   2098
Toy Story (1995)                                                         2077
                                                                         ...
Last of the High Kings, The (a.k.a. Summer Fling) (1996)                    1
Proposition, The (1998)                                                     1
Alley Cats, The (1968)                                                      1
Mouth to Mouth (Boca a boca) (1995)                                         1
White Boys (1999)                                                           1
One Man's Hero (1999)                                                       1
Project Moon Base (1953)                                                    1
An Unforgettable Summer (1994)                                              1
Hungarian Fairy Tale, A (1987)                                              1
Broken Vessels (1998)                                                       1
Telling You (1998)                                                          1
Little Indian, Big City (Un indien dans la ville) (1994)                    1
Bye-Bye (1995)                                                              1
Terror in a Texas Town (1958)                                               1
Mascara (1999)                                                              1
Ten Benny (1997)                                                            1
Voyage to the Beginning of the World (1997)                                 1
Waiting Game, The (2000)                                                    1
Jar, The (Khomreh) (1992)                                                   1
I Don't Want to Talk About It (De eso no se habla) (1993)                   1
Open Season (1996)                                                          1
Waltzes from Vienna (1933)                                                  1
Tashunga (1995)                                                             1
Even Dwarfs Started Small (Auch Zwerge haben klein angefangen) (1971)       1
Target (1995)                                                               1
Anna (1996)                                                                 1
McCullochs, The (1975)                                                      1
Shadows (Cienie) (1988)                                                     1
Night Tide (1961)                                                           1
Another Man's Poison (1952)                                                 1
Length: 3706, dtype: int64

In [43]:
data_gender_hot = data_gender.loc[data_rating_num[data_rating_num > 1000].index] #加入评分次数限制
data_gender_hot.sort_values(by='difference', ascending=False)

Gender,F,M,difference
Title,,,
"Rocky Horror Picture Show, The (1975)",3.673016,3.160131,0.512885
Mary Poppins (1964),4.197740,3.730594,0.467147
Gone with the Wind (1939),4.269841,3.829371,0.440471
"Full Monty, The (1997)",4.113456,3.760976,0.352481
"Little Mermaid, The (1989)",3.975936,3.632375,0.343561
Pretty Woman (1990),3.846914,3.511700,0.335213
Thelma & Louise (1991),3.916268,3.581582,0.334686
Clueless (1995),3.827004,3.514640,0.312365
Ghost (1990),3.698667,3.395194,0.303473
Willy Wonka and the Chocolate Factory (1971),4.063953,3.789474,0.274480
"League of Their Own, A (1992)",3.865497,3.595773,0.269724
When Harry Met Sally... (1989),4.257028,3.987850,0.269178
Titanic (1997),3.764228,3.499051,0.265176
Beauty and the Beast (1991),4.054945,3.797414,0.257531
Romancing the Stone (1984),3.854227,3.632735,0.221493
Erin Brockovich (2000),4.007126,3.796421,0.210705
"American President, The (1995)",3.923483,3.718654,0.204828
"Crying Game, The (1992)",3.869018,3.665865,0.203152
Witness (1985),4.115854,3.941504,0.174349
Independence Day (ID4) (1996),3.651007,3.481145,0.169861
E.T. the Extra-Terrestrial (1982),4.089850,3.920264,0.169586
Galaxy Quest (1999),3.901554,3.733979,0.167575
Star Trek: First Contact (1996),3.849057,3.682149,0.166907
"Thomas Crown Affair, The (1999)",3.763265,3.606635,0.156630
Edward Scissorhands (1990),3.697034,3.543457,0.153577
"Wizard of Oz, The (1939)",4.355030,4.203138,0.151892
Cocoon (1985),3.654709,3.504470,0.150239
Four Weddings and a Funeral (1994),3.834382,3.686508,0.147874
Armageddon (1998),3.310000,3.165934,0.144066
Air Force One (1997),3.699588,3.555822,0.143766
...,...,...,...
Clerks (1994),3.746875,4.005495,-0.258620
GoodFellas (1990),4.072423,4.331279,-0.258855
"Mask, The (1994)",3.081851,3.340757,-0.258907
"Blues Brothers, The (1980)",3.730627,3.992523,-0.261896
"Big Lebowski, The (1998)",3.527897,3.795139,-0.267242
"Godfather, The (1972)",4.314700,4.583333,-0.268634
Pulp Fiction (1994),4.071956,4.346839,-0.274883
Braveheart (1995),4.016484,4.297839,-0.281355
There's Something About Mary (1998),3.692754,3.975634,-0.282880
Rocky (1976),3.711538,3.995657,-0.284118
Saving Private Ryan (1998),4.114783,4.398941,-0.284159
Planet of the Apes (1968),3.465608,3.760534,-0.294926
Austin Powers: International Man of Mystery (1997),3.478873,3.781759,-0.302886
2001: A Space Odyssey (1968),3.825581,4.129738,-0.304156
Groundhog Day (1993),3.735562,4.041358,-0.305796
"Terminator, The (1984)",3.899729,4.205899,-0.306170
Mad Max 2 (a.k.a. The Road Warrior) (1981),3.393701,3.713341,-0.319640
Alien (1979),3.888252,4.216119,-0.327867
Terminator 2: Judgment Day (1991),3.785088,4.115367,-0.330279
Full Metal Jacket (1987),3.821839,4.157407,-0.335568
Apocalypse Now (1979),3.955307,4.294885,-0.339577
Starship Troopers (1997),2.802721,3.181102,-0.378381
Aliens (1986),3.802083,4.186684,-0.384601
"Clockwork Orange, A (1971)",3.757009,4.145813,-0.388803
"Godfather: Part II, The (1974)",4.040936,4.437778,-0.396842
Predator (1987),3.299401,3.706195,-0.406793
Airplane! (1980),3.656566,4.064419,-0.407854
"South Park: Bigger, Longer and Uncut (1999)",3.422481,3.846686,-0.424206
Reservoir Dogs (1992),3.769231,4.213873,-0.444642
Animal House (1978),3.628906,4.167192,-0.538286

In [45]:
data_mean_rating_number = data_mean_rating.loc[data_rating_num[data_rating_num > 1000].index]
data_mean_rating_number_sorted = data_mean_rating_number.sort_values(by='Rating', ascending=False)
data_mean_rating_number_sorted

                                                      Rating
Title
Shawshank Redemption, The (1994)                    4.554558
Godfather, The (1972)                               4.524966
Usual Suspects, The (1995)                          4.517106
Schindler's List (1993)                             4.510417
Raiders of the Lost Ark (1981)                      4.477725
Rear Window (1954)                                  4.476190
Star Wars: Episode IV - A New Hope (1977)           4.453694
Dr. Strangelove or: How I Learned to Stop Worry...  4.449890
Casablanca (1942)                                   4.412822
Sixth Sense, The (1999)                             4.406263
Maltese Falcon, The (1941)                          4.395973
One Flew Over the Cuckoo's Nest (1975)              4.390725
Citizen Kane (1941)                                 4.388889
North by Northwest (1959)                           4.384030
Godfather: Part II, The (1974)                      4.357565
Silence of the Lambs, The (1991)                    4.351823
Chinatown (1974)                                    4.339241
Saving Private Ryan (1998)                          4.337354
Monty Python and the Holy Grail (1974)              4.335210
Life Is Beautiful (La Vita � bella) (1997)          4.329861
Sting, The (1973)                                   4.320305
American Beauty (1999)                              4.317386
Matrix, The (1999)                                  4.315830
Princess Bride, The (1987)                          4.303710
Boat, The (Das Boot) (1981)                         4.302697
Star Wars: Episode V - The Empire Strikes Back ...  4.292977
Pulp Fiction (1994)                                 4.278213
GoodFellas (1990)                                   4.275196
Blade Runner (1982)                                 4.273333
Fargo (1996)                                        4.254676
...                                                      ...
Superman (1978)                                     3.536825
Sleepy Hollow (1999)                                3.516886
Independence Day (ID4) (1996)                       3.510405
Talented Mr. Ripley, The (1999)                     3.503381
Ghost (1990)                                        3.496441
Stargate (1994)                                     3.490143
Robocop (1987)                                      3.451587
Fly, The (1986)                                     3.440710
Mission: Impossible (1996)                          3.432875
Splash (1984)                                       3.430782
Star Wars: Episode I - The Phantom Menace (1999)    3.409778
Star Trek VI: The Undiscovered Country (1991)       3.409590
Face/Off (1997)                                     3.401126
Austin Powers: The Spy Who Shagged Me (1999)        3.388424
Perfect Storm, The (2000)                           3.351431
Back to the Future Part II (1989)                   3.343696
Mummy, The (1999)                                   3.321748
Rocky Horror Picture Show, The (1975)               3.291160
Mask, The (1994)                                    3.279050
Back to the Future Part III (1990)                  3.242160
Mission: Impossible 2 (2000)                        3.195735
Armageddon (1998)                                   3.191892
Twister (1996)                                      3.173874
Starship Troopers (1997)                            3.133276
Lost World: Jurassic Park, The (1997)               3.036653
Blair Witch Project, The (1999)                     3.031528
Arachnophobia (1990)                                3.002926
Batman Returns (1992)                               2.976722
Honey, I Shrunk the Kids (1989)                     2.933014
Mars Attacks! (1996)                                2.900372

[207 rows x 1 columns]